### ISSUE TITLE
Grass Path Block lighting glitch

### ISSUE THREAD

**Issue by kenandler** [Kirito2001/openlowergrass#3]
![2019-07-29_16 49 44](https://user-images.githubusercontent.com/42678618/62090297-2b33f100-b221-11e9-9c1e-5984a638267f.png)

**Comment by Kirito2001** [comment]
This is Minecraft's default textures, OLG doesn't change textures itself, and therefore it looks weird, if you're going to use OLG for vanilla textures I'd just recommend Xisumavoid's Vanilla Tweaks.
